V = 0.6
DISTNAME = skroll-${V}
COMMENT = utility to scroll piped text, uses pledge(2)
HOMEPAGE = https://www.z3bra.org/skroll
MAINTAINER = Mitch Weaver <mitch@wvr.sh>
CATEGORIES = misc
PERMIT_PACKAGE = Yes
EXTRACT_SUFX = .tar.bz2

MASTER_SITES=https://dl.z3bra.org/releases/

.include <bsd.port.mk>
